version: '3.8'

services:
  task:
    image: gilgamesh06/task:latest
    port:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-task:5432/task
      - SPRING_DATASOURCE_USERNAME=Solus
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - db-task
    networks:
      - my_network
  
  db-task:
    image: postgres:16
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=Solus
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    volumes:
      - data-task:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  data-task:

networks:
  my_network:
    driver: bridge